Added new log-emoji.js
ceadoor/HacktoberFest-2020 pull request #116
Opened 2020-10-25 12:06 UTC by laurenziello

Created javascript fancy log

2020-10-25 13:57 UTC, janusjerom approved these changes
Please do keep the format for the file.
// PROGRAM-NAME : Hello, World!
// By John Doe
// PROGRAM-CODE :

2020-10-25 14:01 UTC, janusjerom requested changes
Please update by keeping the format. Please change your file contents
// PROGRAM-NAME : Hello, World!
// By John Doe
// PROGRAM-CODE :

2020-10-25 16:28 UTC, laurenziello commented
@janusjerom just took your comment :) Thanks

2020-10-26 19:56 UTC, janusjerom approved these changes
Thank you for your PR

2020-10-26 19:56 UTC, merged